name: Bug Report
description: Report a bug found in Uranium
title: "[Bug]: "
labels: "bug :beetle:"
body:
    - type: checkboxes
      attributes:
          label: Preflight Checklist
          description: Please ensure you've completed all of the following.
          options:
              - label: I have read the [Contributing Guidelines]() for this project.
                required: true
              - label: I agree to follow the [Code of Conduct]() that this project adheres to.
                required: true
              - label: I have searched the [issue tracker](https://www.github.com/Uranium-Development/Uranium/issues) for a feature request that matches the one I want to file, without success.
                required: true
    - type: input
      attributes:
          label: Uranium Version
          description: What version of Uranium did you find this bug on?
          placeholder: 1.0.0
      validations:
          required: true
    - type: dropdown
      attributes:
          label: What operating system are you using?
          options:
              - Windows
              - macOS
              - Linux
              - Other (specify below)
      validations:
          required: true
    - type: input
      attributes:
          label: Operating System Version
          description: What OS version are you using? On Windows, click Start button > Settings > System > About. On macOS, click the Apple Menu > About This Mac. On Linux, use lsb_release or uname -a.
          placeholder: "ex: Windows 10 build 19042 or macOS Big Sur 11.0.0"
      validations:
          required: true
    - type: dropdown
      attributes:
          label: What arch are you using?
          options:
              - x64
              - ia32
              - arm64 (including Apple Silicon)
              - Other (specify below)
      validations:
          required: true
    - type: input
      attributes:
          label: Last Known Working Uranium version
          description: What is the last version of Uranium this worked in?
          placeholder: 1.0.0
      attributes:
          label: Expected Behavior
          description: A clear and concise description of what you expected to happen.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Actual Behavior
          description: A clear description of what actually happens.
      validations:
          required: true
    - type: textarea
      attributes:
          label: How to Reproduce
          description: If you can reproduce the issue in a standalone test case, specify how to do so below.
          placeholder: To reproduce you have to...
    